In [141]:
import torch

# Before backbone reshaping

In [142]:
x = torch.tensor([[[[-1.1565, -1.1604,  0.1348, -0.4363,  0.0636, -0.6904, -1.2410,
            1.1792],
          [ 0.3455,  0.1169,  0.1134,  0.5073, -1.5005,  1.9755,  0.0662,
            0.2456],
          [-0.2203,  0.4780, -1.3791,  0.6597, -1.7515, -0.4427, -1.8942,
           -0.2927],
          [ 0.5153,  1.6545, -0.0947,  1.1596, -2.3727,  0.4592, -0.6436,
            1.3063],
          [ 1.1441, -1.2184,  0.2395, -1.7865,  1.7953,  0.7927, -0.4405,
            0.7036],
          [ 1.0568,  0.0178,  0.2352,  0.0496, -0.0948, -1.4319,  0.9348,
            0.5739]]],


        [[[ 1.2631, -0.8306,  0.5323,  0.5591, -1.7800,  0.5554, -0.6738,
           -0.1680],
          [-0.0754,  0.9501, -0.2558,  1.5156, -0.0614, -1.5024, -0.7102,
            0.2065],
          [-1.8878,  0.5077, -0.2627, -0.7277,  0.0871, -2.9522,  1.6734,
            1.0364],
          [ 1.7067, -0.4461,  1.2776,  0.5163,  0.9681, -1.1372, -0.5742,
           -1.0085],
          [-0.7302,  1.0499,  1.5723, -0.8061,  0.4974, -0.4010,  0.5745,
           -0.8268],
          [ 0.0809,  0.5157, -0.5276,  0.3849, -1.1059, -0.1943,  0.9247,
            0.9613]]]])
x_orig = x.clone()

In [143]:
x.shape

torch.Size([2, 1, 6, 8])

In [144]:
x

tensor([[[[-1.1565, -1.1604,  0.1348, -0.4363,  0.0636, -0.6904, -1.2410,
            1.1792],
          [ 0.3455,  0.1169,  0.1134,  0.5073, -1.5005,  1.9755,  0.0662,
            0.2456],
          [-0.2203,  0.4780, -1.3791,  0.6597, -1.7515, -0.4427, -1.8942,
           -0.2927],
          [ 0.5153,  1.6545, -0.0947,  1.1596, -2.3727,  0.4592, -0.6436,
            1.3063],
          [ 1.1441, -1.2184,  0.2395, -1.7865,  1.7953,  0.7927, -0.4405,
            0.7036],
          [ 1.0568,  0.0178,  0.2352,  0.0496, -0.0948, -1.4319,  0.9348,
            0.5739]]],


        [[[ 1.2631, -0.8306,  0.5323,  0.5591, -1.7800,  0.5554, -0.6738,
           -0.1680],
          [-0.0754,  0.9501, -0.2558,  1.5156, -0.0614, -1.5024, -0.7102,
            0.2065],
          [-1.8878,  0.5077, -0.2627, -0.7277,  0.0871, -2.9522,  1.6734,
            1.0364],
          [ 1.7067, -0.4461,  1.2776,  0.5163,  0.9681, -1.1372, -0.5742,
           -1.0085],
          [-0.7302,  1.0499,  1.5723, -0.8061,

In [145]:
patch_size = 2

In [146]:
B, C, H, W = x.shape
P = patch_size
B, C, H, W, P

(2, 1, 6, 8, 2)

In [147]:
# Crop to patch size multiplier as in PatchEmbed
x = x[:, :H // P * P, :W // P * P]

In [148]:
x.shape

torch.Size([2, 1, 6, 8])

In [149]:
x

tensor([[[[-1.1565, -1.1604,  0.1348, -0.4363,  0.0636, -0.6904, -1.2410,
            1.1792],
          [ 0.3455,  0.1169,  0.1134,  0.5073, -1.5005,  1.9755,  0.0662,
            0.2456],
          [-0.2203,  0.4780, -1.3791,  0.6597, -1.7515, -0.4427, -1.8942,
           -0.2927],
          [ 0.5153,  1.6545, -0.0947,  1.1596, -2.3727,  0.4592, -0.6436,
            1.3063],
          [ 1.1441, -1.2184,  0.2395, -1.7865,  1.7953,  0.7927, -0.4405,
            0.7036],
          [ 1.0568,  0.0178,  0.2352,  0.0496, -0.0948, -1.4319,  0.9348,
            0.5739]]],


        [[[ 1.2631, -0.8306,  0.5323,  0.5591, -1.7800,  0.5554, -0.6738,
           -0.1680],
          [-0.0754,  0.9501, -0.2558,  1.5156, -0.0614, -1.5024, -0.7102,
            0.2065],
          [-1.8878,  0.5077, -0.2627, -0.7277,  0.0871, -2.9522,  1.6734,
            1.0364],
          [ 1.7067, -0.4461,  1.2776,  0.5163,  0.9681, -1.1372, -0.5742,
           -1.0085],
          [-0.7302,  1.0499,  1.5723, -0.8061,

`tensor.unfold(d, p, s)` extracts patches along dimention `d` with size `p` and stride `s`. The output is a tensor of shape `(*, n, ..., p)` where `n` is the new size of dimention `d` = the number of patches and new last dimention corresponds to each patch.

In [150]:
x.unfold(2, P, P).shape

torch.Size([2, 1, 3, 8, 2])

In [151]:
x.unfold(2, P, P)

tensor([[[[[-1.1565,  0.3455],
           [-1.1604,  0.1169],
           [ 0.1348,  0.1134],
           [-0.4363,  0.5073],
           [ 0.0636, -1.5005],
           [-0.6904,  1.9755],
           [-1.2410,  0.0662],
           [ 1.1792,  0.2456]],

          [[-0.2203,  0.5153],
           [ 0.4780,  1.6545],
           [-1.3791, -0.0947],
           [ 0.6597,  1.1596],
           [-1.7515, -2.3727],
           [-0.4427,  0.4592],
           [-1.8942, -0.6436],
           [-0.2927,  1.3063]],

          [[ 1.1441,  1.0568],
           [-1.2184,  0.0178],
           [ 0.2395,  0.2352],
           [-1.7865,  0.0496],
           [ 1.7953, -0.0948],
           [ 0.7927, -1.4319],
           [-0.4405,  0.9348],
           [ 0.7036,  0.5739]]]],



        [[[[ 1.2631, -0.0754],
           [-0.8306,  0.9501],
           [ 0.5323, -0.2558],
           [ 0.5591,  1.5156],
           [-1.7800, -0.0614],
           [ 0.5554, -1.5024],
           [-0.6738, -0.7102],
           [-0.1680,  0.2065]

Applying `unfold` sequentially to `H` and `W` dimentions result in one before last dimention forresponding to patch `H` and last dimention for `W` (both sizes equal to `P` here). 

In [152]:
x.unfold(2, P, P).unfold(3, P, P).shape

torch.Size([2, 1, 3, 4, 2, 2])

In [153]:
x.unfold(2, P, P).unfold(3, P, P)

tensor([[[[[[-1.1565, -1.1604],
            [ 0.3455,  0.1169]],

           [[ 0.1348, -0.4363],
            [ 0.1134,  0.5073]],

           [[ 0.0636, -0.6904],
            [-1.5005,  1.9755]],

           [[-1.2410,  1.1792],
            [ 0.0662,  0.2456]]],


          [[[-0.2203,  0.4780],
            [ 0.5153,  1.6545]],

           [[-1.3791,  0.6597],
            [-0.0947,  1.1596]],

           [[-1.7515, -0.4427],
            [-2.3727,  0.4592]],

           [[-1.8942, -0.2927],
            [-0.6436,  1.3063]]],


          [[[ 1.1441, -1.2184],
            [ 1.0568,  0.0178]],

           [[ 0.2395, -1.7865],
            [ 0.2352,  0.0496]],

           [[ 1.7953,  0.7927],
            [-0.0948, -1.4319]],

           [[-0.4405,  0.7036],
            [ 0.9348,  0.5739]]]]],




        [[[[[ 1.2631, -0.8306],
            [-0.0754,  0.9501]],

           [[ 0.5323,  0.5591],
            [-0.2558,  1.5156]],

           [[-1.7800,  0.5554],
            [-0.0614, -1.5024]],



In [154]:
# Extract patches
x = x \
    .unfold(2, P, P) \
    .unfold(3, P, P)

In [155]:
x.shape

torch.Size([2, 1, 3, 4, 2, 2])

In [156]:
x

tensor([[[[[[-1.1565, -1.1604],
            [ 0.3455,  0.1169]],

           [[ 0.1348, -0.4363],
            [ 0.1134,  0.5073]],

           [[ 0.0636, -0.6904],
            [-1.5005,  1.9755]],

           [[-1.2410,  1.1792],
            [ 0.0662,  0.2456]]],


          [[[-0.2203,  0.4780],
            [ 0.5153,  1.6545]],

           [[-1.3791,  0.6597],
            [-0.0947,  1.1596]],

           [[-1.7515, -0.4427],
            [-2.3727,  0.4592]],

           [[-1.8942, -0.2927],
            [-0.6436,  1.3063]]],


          [[[ 1.1441, -1.2184],
            [ 1.0568,  0.0178]],

           [[ 0.2395, -1.7865],
            [ 0.2352,  0.0496]],

           [[ 1.7953,  0.7927],
            [-0.0948, -1.4319]],

           [[-0.4405,  0.7036],
            [ 0.9348,  0.5739]]]]],




        [[[[[ 1.2631, -0.8306],
            [-0.0754,  0.9501]],

           [[ 0.5323,  0.5591],
            [-0.2558,  1.5156]],

           [[-1.7800,  0.5554],
            [-0.0614, -1.5024]],



We expect the first patch from the original to be the first patch in the unfolded tensor and second (in row order) being the second and so on.

In [157]:
assert torch.allclose(
    x_orig[0, 0, :2, :2], 
    x[0, 0, 0, 0]
)
assert torch.allclose(
    x_orig[0, 0, :2, 2:4], 
    x[0, 0, 0, 1]
)
assert torch.allclose(
    x_orig[0, 0, 2:4, 2:4], 
    x[0, 0, 1, 1]
)

In [158]:
# Concat to batch dimension
# (B, C, H_patches, W_patches, patch_size, patch_size) -> 
# (B * H_patches * W_patches, C, patch_size, patch_size)
H_patches, W_patches = x.shape[2:4]
H_patches, W_patches

(3, 4)

In [159]:
x.reshape(B * H_patches * W_patches, C, P, P).shape

torch.Size([24, 1, 2, 2])

In [160]:
x = x.reshape(B * H_patches * W_patches, C, P, P)

In [161]:
x.shape

torch.Size([24, 1, 2, 2])

In [162]:
x

tensor([[[[-1.1565, -1.1604],
          [ 0.3455,  0.1169]]],


        [[[ 0.1348, -0.4363],
          [ 0.1134,  0.5073]]],


        [[[ 0.0636, -0.6904],
          [-1.5005,  1.9755]]],


        [[[-1.2410,  1.1792],
          [ 0.0662,  0.2456]]],


        [[[-0.2203,  0.4780],
          [ 0.5153,  1.6545]]],


        [[[-1.3791,  0.6597],
          [-0.0947,  1.1596]]],


        [[[-1.7515, -0.4427],
          [-2.3727,  0.4592]]],


        [[[-1.8942, -0.2927],
          [-0.6436,  1.3063]]],


        [[[ 1.1441, -1.2184],
          [ 1.0568,  0.0178]]],


        [[[ 0.2395, -1.7865],
          [ 0.2352,  0.0496]]],


        [[[ 1.7953,  0.7927],
          [-0.0948, -1.4319]]],


        [[[-0.4405,  0.7036],
          [ 0.9348,  0.5739]]],


        [[[ 1.2631, -0.8306],
          [-0.0754,  0.9501]]],


        [[[ 0.5323,  0.5591],
          [-0.2558,  1.5156]]],


        [[[-1.7800,  0.5554],
          [-0.0614, -1.5024]]],


        [[[-0.6738, -0.1680],
          

In [163]:
H_patches, W_patches

(3, 4)

In [164]:
assert torch.allclose(
    x_orig[0, 0, :2, :2],
    x[0]
)
assert torch.allclose(
    x_orig[0, 0, :2, 2:4],
    x[1]
)
assert torch.allclose(
    x_orig[0, 0, :2, 4:6],
    x[2]
)
assert torch.allclose(
    x_orig[0, 0, :2, 6:8],
    x[3]
)
assert torch.allclose(
    x_orig[0, 0, 2:4, :2],
    x[4]
)

In [165]:
x.shape

torch.Size([24, 1, 2, 2])

# After backbone reshaping

In [178]:
x = torch.tensor(
       [[0.2295, 0.4275, 0.0133, 0.1534, 0.0362],
        [0.2156, 0.1242, 0.9368, 0.5264, 0.1139],
        [0.7788, 0.6485, 0.6916, 0.4283, 0.2095],
        [0.7724, 0.8878, 0.1865, 0.3467, 0.4742],
        [0.1125, 0.7691, 0.6569, 0.9564, 0.5923],
        [0.2368, 0.7427, 0.8742, 0.6825, 0.8669],
        [0.3325, 0.1351, 0.4336, 0.4080, 0.7095],
        [0.4388, 0.2767, 0.3081, 0.7695, 0.7315],
        [0.8080, 0.5337, 0.3601, 0.5056, 0.0583],
        [0.4156, 0.0110, 0.5817, 0.0018, 0.6167],
        [0.0210, 0.5488, 0.7290, 0.0382, 0.7331],
        [0.8665, 0.9017, 0.3889, 0.9789, 0.8334],
        [0.3650, 0.1587, 0.5106, 0.7355, 0.9270],
        [0.2939, 0.4088, 0.4134, 0.9904, 0.3219],
        [0.0369, 0.2202, 0.9024, 0.7569, 0.1187],
        [0.7938, 0.1773, 0.6068, 0.6999, 0.1728],
        [0.2812, 0.6866, 0.3939, 0.8907, 0.9239],
        [0.5513, 0.6075, 0.2802, 0.9140, 0.7546],
        [0.7956, 0.6102, 0.4988, 0.9960, 0.0373],
        [0.3843, 0.9964, 0.7041, 0.5303, 0.8602],
        [0.8636, 0.8806, 0.3060, 0.7096, 0.9293],
        [0.5921, 0.4600, 0.3340, 0.2115, 0.9943],
        [0.5923, 0.9883, 0.8644, 0.8937, 0.9806],
        [0.1931, 0.1426, 0.9869, 0.6961, 0.2664]])
x_orig = x.clone()

In [179]:
x.shape

torch.Size([24, 5])

In [180]:
x

tensor([[0.2295, 0.4275, 0.0133, 0.1534, 0.0362],
        [0.2156, 0.1242, 0.9368, 0.5264, 0.1139],
        [0.7788, 0.6485, 0.6916, 0.4283, 0.2095],
        [0.7724, 0.8878, 0.1865, 0.3467, 0.4742],
        [0.1125, 0.7691, 0.6569, 0.9564, 0.5923],
        [0.2368, 0.7427, 0.8742, 0.6825, 0.8669],
        [0.3325, 0.1351, 0.4336, 0.4080, 0.7095],
        [0.4388, 0.2767, 0.3081, 0.7695, 0.7315],
        [0.8080, 0.5337, 0.3601, 0.5056, 0.0583],
        [0.4156, 0.0110, 0.5817, 0.0018, 0.6167],
        [0.0210, 0.5488, 0.7290, 0.0382, 0.7331],
        [0.8665, 0.9017, 0.3889, 0.9789, 0.8334],
        [0.3650, 0.1587, 0.5106, 0.7355, 0.9270],
        [0.2939, 0.4088, 0.4134, 0.9904, 0.3219],
        [0.0369, 0.2202, 0.9024, 0.7569, 0.1187],
        [0.7938, 0.1773, 0.6068, 0.6999, 0.1728],
        [0.2812, 0.6866, 0.3939, 0.8907, 0.9239],
        [0.5513, 0.6075, 0.2802, 0.9140, 0.7546],
        [0.7956, 0.6102, 0.4988, 0.9960, 0.0373],
        [0.3843, 0.9964, 0.7041, 0.5303, 0.8602],


In [181]:
x.reshape(B, H_patches * W_patches, *x.shape[1:]).shape

torch.Size([2, 12, 5])

In [182]:
x.reshape(B, H_patches * W_patches, *x.shape[1:])

tensor([[[0.2295, 0.4275, 0.0133, 0.1534, 0.0362],
         [0.2156, 0.1242, 0.9368, 0.5264, 0.1139],
         [0.7788, 0.6485, 0.6916, 0.4283, 0.2095],
         [0.7724, 0.8878, 0.1865, 0.3467, 0.4742],
         [0.1125, 0.7691, 0.6569, 0.9564, 0.5923],
         [0.2368, 0.7427, 0.8742, 0.6825, 0.8669],
         [0.3325, 0.1351, 0.4336, 0.4080, 0.7095],
         [0.4388, 0.2767, 0.3081, 0.7695, 0.7315],
         [0.8080, 0.5337, 0.3601, 0.5056, 0.0583],
         [0.4156, 0.0110, 0.5817, 0.0018, 0.6167],
         [0.0210, 0.5488, 0.7290, 0.0382, 0.7331],
         [0.8665, 0.9017, 0.3889, 0.9789, 0.8334]],

        [[0.3650, 0.1587, 0.5106, 0.7355, 0.9270],
         [0.2939, 0.4088, 0.4134, 0.9904, 0.3219],
         [0.0369, 0.2202, 0.9024, 0.7569, 0.1187],
         [0.7938, 0.1773, 0.6068, 0.6999, 0.1728],
         [0.2812, 0.6866, 0.3939, 0.8907, 0.9239],
         [0.5513, 0.6075, 0.2802, 0.9140, 0.7546],
         [0.7956, 0.6102, 0.4988, 0.9960, 0.0373],
         [0.3843, 0.9964, 0.7

In [183]:
# Reshape back as expected from PatchEmbed
# (B * H_patches * W_patches, *backbone_out_shape) ->
# (B, H * W, *backbone_out_shape)
x = x.reshape(B, H_patches * W_patches, *x.shape[1:])

In [184]:
x.shape

torch.Size([2, 12, 5])

In [185]:
x.reshape(B, H_patches,  W_patches, 5).shape

torch.Size([2, 3, 4, 5])

In [186]:
x.reshape(B, H_patches,  W_patches, 5)

tensor([[[[0.2295, 0.4275, 0.0133, 0.1534, 0.0362],
          [0.2156, 0.1242, 0.9368, 0.5264, 0.1139],
          [0.7788, 0.6485, 0.6916, 0.4283, 0.2095],
          [0.7724, 0.8878, 0.1865, 0.3467, 0.4742]],

         [[0.1125, 0.7691, 0.6569, 0.9564, 0.5923],
          [0.2368, 0.7427, 0.8742, 0.6825, 0.8669],
          [0.3325, 0.1351, 0.4336, 0.4080, 0.7095],
          [0.4388, 0.2767, 0.3081, 0.7695, 0.7315]],

         [[0.8080, 0.5337, 0.3601, 0.5056, 0.0583],
          [0.4156, 0.0110, 0.5817, 0.0018, 0.6167],
          [0.0210, 0.5488, 0.7290, 0.0382, 0.7331],
          [0.8665, 0.9017, 0.3889, 0.9789, 0.8334]]],


        [[[0.3650, 0.1587, 0.5106, 0.7355, 0.9270],
          [0.2939, 0.4088, 0.4134, 0.9904, 0.3219],
          [0.0369, 0.2202, 0.9024, 0.7569, 0.1187],
          [0.7938, 0.1773, 0.6068, 0.6999, 0.1728]],

         [[0.2812, 0.6866, 0.3939, 0.8907, 0.9239],
          [0.5513, 0.6075, 0.2802, 0.9140, 0.7546],
          [0.7956, 0.6102, 0.4988, 0.9960, 0.0373],
  

In [187]:
x = x.reshape(B, H_patches,  W_patches, 5)

In [189]:
assert torch.allclose(
    x_orig[0],
    x[0, 0, 0]
)
assert torch.allclose(
    x_orig[1],
    x[0, 0, 1]
)
assert torch.allclose(
    x_orig[2],
    x[0, 0, 2]
)
assert torch.allclose(
    x_orig[3],
    x[0, 0, 3]
)
assert torch.allclose(
    x_orig[4],
    x[0, 1, 0]
)
assert torch.allclose(
    x_orig[5],
    x[0, 1, 1]
)